/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Customization3D.java
 *
 * Created on Apr 30, 2011, 10:48:20 AM
 */

package capstone3daudiodemo;

import java.io.File;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.DataLine;

/**
 *
 * @author Ian
 */
public class Customization3D extends javax.swing.JFrame {

    /** Creates new form Customization3D */
    public Customization3D() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(capstone3daudiodemo.Capstone3DAudioDemoApp.class).getContext().getResourceMap(Customization3D.class);
        jLabel1.setIcon(resourceMap.getIcon("jLabel1.icon")); // NOI18N
        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N

        jLabel2.setIcon(resourceMap.getIcon("jLabel2.icon")); // NOI18N
        jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
        jLabel2.setName("jLabel2"); // NOI18N

        jLabel3.setIcon(resourceMap.getIcon("jLabel3.icon")); // NOI18N
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        jLabel4.setIcon(resourceMap.getIcon("jLabel4.icon")); // NOI18N
        jLabel4.setText(resourceMap.getString("jLabel4.text")); // NOI18N
        jLabel4.setName("jLabel4"); // NOI18N

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N

        jLabel6.setIcon(resourceMap.getIcon("jLabel6.icon")); // NOI18N
        jLabel6.setText(resourceMap.getString("jLabel6.text")); // NOI18N
        jLabel6.setName("jLabel6"); // NOI18N

        jButton1.setText(resourceMap.getString("jButton1.text")); // NOI18N
        jButton1.setName("jButton1"); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText(resourceMap.getString("jButton2.text")); // NOI18N
        jButton2.setName("jButton2"); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setName("jButton3"); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText(resourceMap.getString("jButton4.text")); // NOI18N
        jButton4.setName("jButton4"); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setName("jButton5"); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText(resourceMap.getString("jButton6.text")); // NOI18N
        jButton6.setName("jButton6"); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(123, 123, 123))
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(155, 155, 155)
                                .addComponent(jLabel6)))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jButton6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton5)))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addGap(47, 47, 47)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        String HRTFloc1 = "/capstone3audiodemo/resources/"+subjects[currentHRTF]+"_1.wav";
        String HRTFloc2 = "/capstone3daudiodemo/resources/"+subjects[currentHRTF]+"_2.wav";
        String HRTFloc3 = "/capstone3daudiodemo/resources/"+subjects[currentHRTF]+"_3.wav";
        String HRTFloc4 = "/capstone3daudiodemo/resources/"+subjects[currentHRTF]+"_4.wav";

        File soundFile1 = new File(getClass().getResource(HRTFloc1).getFile());
        File soundFile2 = new File(getClass().getResource(HRTFloc2).getFile());
        File soundFile3 = new File(getClass().getResource(HRTFloc3).getFile());
        File soundFile4 = new File(getClass().getResource(HRTFloc4).getFile());

        playSound(jLabel1, soundFile2, c1, m1);
        playSound(jLabel2, soundFile1, c2, m2);
        playSound(jLabel3, soundFile3, c3, m3);
        playSound(jLabel4, soundFile4, c4, m4);


        //Now that all of the sounds have been played
        //Update the mode and change which buttons are visible
        if(mode == 0)
        {
            mode = 1;
            //Reveal great, medium, bad buttons
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
            //Update message to tell user to press button
            jLabel5.setText("Please evaluate how well the sound matched the visual indicators.");
        }
        if(mode == 2)
        {
            mode = 3;
            //Reveal better, worse buttons
            jButton5.setEnabled(true);
            jButton6.setEnabled(true);
            //Update message to tell user to press button
            jLabel5.setText("Please indicate whether the sound matched the indicators better or worse than the previous sound.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        //Excellent button
        mode = 4;
        range = 0;
        //Set message to say you're done and can hit OK
        //Hide all buttons
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
        jButton6.setEnabled(false);
        jLabel5.setText("Your 3D audio has been prepared.  Press OK to save settings.");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //Decent button
        mode = 2;
        currentHRTF = 1;
        //Hide excellent, decent, and bad buttons
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jLabel5.setText("A new 3D sound sample has been prepared.  Press Test Sound to hear the sample.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //Poor button
        mode = 2;
        currentHRTF = numHRTFs-1;
        direction = -1;
        //Hide excellent, decent, and bad buttons
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        jLabel5.setText("A new 3D sound sample has been prepared.  Press Test Sound to hear the sample.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //Better button
        currentHRTF += (direction*range);
        if(currentHRTF<0)
            currentHRTF=0;
        if(currentHRTF>=numHRTFs)
            currentHRTF = numHRTFs-1;
        range = range/2;
        if(range>0)
        {
            mode = 2;
            //Hide better/worse buttons
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jLabel5.setText("A new 3D sound sample has been prepared.  Press Test Sound to hear the sample.");
        }
        else
        {
            mode = 4;
            //Hide all buttons
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jLabel5.setText("Your 3D audio has been prepared.  Press OK to save settings.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //Worse button
        direction *= -1;
        if(currentHRTF == numHRTFs-1 && range>0)
            direction = -1;
        if(currentHRTF==1 && range>0)
            direction = 1;
        currentHRTF += (direction*range);
        if(currentHRTF<0)
            currentHRTF=0;
        if(currentHRTF>=numHRTFs)
            currentHRTF = numHRTFs-1;
        range = range/2;
        if(range>0)
        {
            mode = 2;
            //Hide better/worse buttons
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jLabel5.setText("A new 3D sound sample has been prepared.  Press Test Sound to hear the sample.");
        }
        else
        {
            mode = 4;
            //Hide all buttons
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
            jButton5.setEnabled(false);
            jButton6.setEnabled(false);
            jLabel5.setText("Your 3D audio has been prepared.  Press OK to save settings.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void playSound(javax.swing.JLabel label, File soundfile, javax.swing.ImageIcon color, javax.swing.ImageIcon mono)
    {
        AudioInputStream sound = null;
        try{sound = AudioSystem.getAudioInputStream(soundfile);}
        catch(Exception e) {System.out.println("Failed to load sound file");}

        // load the sound into memory (a Clip)
        DataLine.Info info = new DataLine.Info(Clip.class, sound.getFormat());
        Clip clip = null;
        try {clip = (Clip) AudioSystem.getLine(info);
        clip.open(sound); }
        catch(Exception e) {}

        label.setIcon(color);
        label.paintImmediately(0,0,50,50);

        LineListenerEnd listener = new LineListenerEnd();
        listener.finished = false;
        clip.addLineListener(listener);

        // play the sound clip
        clip.start();
        int i=0;
        while(listener.finished == false) {try {
                Thread.sleep(1);
            }catch(InterruptedException e) {
        } }
        label.setIcon(mono);
        label.paintImmediately(0,0,50,50);
    }

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customization3D().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables

    //Ian's variables
    int mode = 0;
    int numHRTFs = 10;
    int currentHRTF = 0;
    int range = 3;
    int direction = 1; //-1 left, 1 right

    String subjects[] = {"003", "044", "028", "033", "020", "040", "021", "027", "010", "018"};

    javax.swing.ImageIcon m1 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker1m.jpg"));
    javax.swing.ImageIcon m2 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker2m.jpg"));
    javax.swing.ImageIcon m3 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker3m.jpg"));
    javax.swing.ImageIcon m4 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker4m.jpg"));
    javax.swing.ImageIcon c1 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker1c.jpg"));
    javax.swing.ImageIcon c2 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker2c.jpg"));
    javax.swing.ImageIcon c3 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker3c.jpg"));
    javax.swing.ImageIcon c4 = new javax.swing.ImageIcon(getClass().getResource("/capstone3daudiodemo/resources/speaker4c.jpg"));


}
